services:
  - type: web
    name: eventmasterpro
    env: node
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: MPESA_ENVIRONMENT
        value: sandbox
      - key: MPESA_CALLBACK_URL
        value: https://eventpro-70gf.onrender.com/api/payments/mpesa/callback 